nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org"

npmAlwaysAuth: false

enableGlobalCache: false

compressionLevel: mixed

enableTelemetry: false

# Ensure we always use the public registry
npmScopes:
  "": 
    npmRegistryServer: "https://registry.npmjs.org"