nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org"

npmAlwaysAuth: false

enableGlobalCache: false

compressionLevel: mixed

enableTelemetry: false

# Force all packages to use public npm registry
npmScopes:
  "@radix-ui":
    npmRegistryServer: "https://registry.npmjs.org"
  "@supabase":
    npmRegistryServer: "https://registry.npmjs.org"
  "@tiptap":
    npmRegistryServer: "https://registry.npmjs.org"
  "@dnd-kit":
    npmRegistryServer: "https://registry.npmjs.org"
  "@floating-ui":
    npmRegistryServer: "https://registry.npmjs.org"
  "@types":
    npmRegistryServer: "https://registry.npmjs.org"
  "":
    npmRegistryServer: "https://registry.npmjs.org"

# Disable any private registry lookups
npmPublishRegistry: "https://registry.npmjs.org"
npmAuditRegistry: "https://registry.npmjs.org"